version: '3.3'

services:
  aws_s3:
    image: localstack/localstack
    container_name: kotlin_playground_aws_s3
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './localstack:/docker-entrypoint-initaws.d'