version: '3.3'

services:
  aws_s3:
    image: localstack/localstack:0.11.3
    container_name: kotlin_playground_aws_s3
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './localstack:/docker-entrypoint-initaws.d'
    ports:
      - '0.0.0.0:4566:4566'