server:
  port: 6000
  shutdown: graceful

spring:
  application:
    name: Kotlin Playground
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/kotlin_playground
    username: root
    password:

  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/changelog.xml

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true