server:
  port: 6000
  shutdown: graceful

spring:
  application:
    name: Kotlin Playground
  profiles:
    active: prod
  banner:
    location: classpath:banner.txt

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/kotlin_playground
    username: root
    password:

  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/changelog.xml

management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

application:
  aws:
    s3:
      employee-document:
        bucket: employee-documents