server:
  port: 6000
  shutdown: graceful

spring:
  application:
    name: Kotlin Playground

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/kotlin_playground
    username: root
    password:

  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/changelog.xml

  profiles:
    active: prod